apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterlib-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/jupyterlib  # For local storage, change as necessary
