apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-service
spec:
  selector:
    app: jupyterlab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: LoadBalancer  # Use NodePort if you don't have a cloud provider with LoadBalancer support
