apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterlab-notebooks-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/jupyterlab/notebooks
